[package]
name = "ffav"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
ffav-sys = {path = "../ffav-sys"}
num-rational = "0.4.0"
static_assertions = "1.1.0"
thiserror = "1.0.28"
